spring:
  application:
    name: notifcationApiService

app:
  pubsub:
    kafka:
      enabled: true
      topic: ingest
      send-timeout-ms: 5000
    sqs:
      enabled: false
    mqtt:
      enabled: false
    rabbitmq:
      enabled: false
