spring:
  application:
    name: notifcationApiService

app:
  pubsub:
    kafka:
      enabled: true
      send-timeout-ms: 5000

      topics:
        ingest-topic: notification.ingest
        audit-topic: notification.audit

    sqs:
      enabled: false

    mqtt:
      enabled: false

    rabbitmq:
      enabled: false
